import 'dotenv/config'

export const env = {
  MONGODB_URI: process.env.MONGODB_URI,
  DATABASE_NAME: process.env.DATABASE_NAME,
  DATABASE_PASSWORDS: process.env.DATABASE_PASSWORDS,
  LOCAL_DEV_APP_HOST: process.env.LOCAL_DEV_APP_HOST,
  LOCAL_DEV_APP_PORT: process.env.LOCAL_DEV_APP_PORT,
  BUILD_MODE: process.env.BUILD_MODE,
  AUTHOR: process.env.AUTHOR,
  MAILER_SEND_API_KEY: process.env.MAILER_SEND_API_KEY,
  MAILER_ADMIN_SENDER_EMAIL: process.env.MAILER_ADMIN_SENDER_EMAIL,
  MAILER_ADMIN_SENDER_NAME: process.env.MAILER_ADMIN_SENDER_NAME
}
